name: Rust Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build release
      run: cargo build --release --verbose
    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: LeveldbCat-windows
        path: target/release/LeveldbCat.exe
        if-no-files-found: error
